[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Authorize users to upload files with messages
multi_modal = true

# Allows user to use speech to text
[features.speech_to_text]
    enabled = false
    # See all languages here https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
    language = "es-PE"

[UI]
# Name of the app and chatbot.
name = "Qhali"

# Show the readme while the thread is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
description = "Medical Chatbot capable of diagnosis"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/pollitoconpapass/Medical-Bot-Proto"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
#custom_css = "/public/custom.css"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    background = "#f5f0f0" # -> white
    paper = "#033b27"   # -> mid-dark green

    [UI.theme.light.primary]
        main = "#bcc904"  # -> Kinda greeny yellow
        dark = "#033b27"
        light = "#202120"  

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
    background = "#1b1c1b"  #-> gray-black
    paper = "#033b27"  # -> mid-dark green

    [UI.theme.dark.primary]
        main = "#bcc904"  # -> kinda grenny yellow
        dark = "#202120"  # -> black
        light = "#033b27"  # -> green 


[meta]
generated_by = "1.0.101"



# background = Background color
# paper = Top panel and query space color
# main = Buttons and links color
# dark = Selected dark "shadow" color
# light = Selected light "shadow" color
